/// sna webcomponent autogenerated file

import IN_BUTTON from './in-button.ts';
import IN_TEXT from './in-text.ts';
import NC_LOGIN from './nc-login.ts';
import NC_NODE from './nc-node.ts';
import UI_FRAME from './ui-frame.ts';
import UI_GROUP from './ui-group.ts';
import UI_METADATA from './ui-metadata.ts';
import UI_PANEL from './ui-panel.ts';
import UI_RACK from './ui-rack.ts';
import UI_TABBED from './ui-tabbed.ts';
import AC_BUTTON from './ac-button.ts';
import IN_COLORIS from './in-coloris.ts';

function DeclareComponents() {
  customElements.define('in-button', IN_BUTTON);
  customElements.define('in-text', IN_TEXT);
  customElements.define('nc-login', NC_LOGIN);
  customElements.define('nc-node', NC_NODE);
  customElements.define('ui-frame', UI_FRAME);
  customElements.define('ui-group', UI_GROUP);
  customElements.define('ui-panel', UI_PANEL);
  customElements.define('ui-rack', UI_RACK);
  customElements.define('ui-tabbed', UI_TABBED);
  customElements.define('ui-metadata', UI_METADATA);
  customElements.define('ac-button', AC_BUTTON);
  customElements.define('in-coloris', IN_COLORIS);
}

export { DeclareComponents };
