# metadata
_schemaVersion: '2.0'
_key: PropertyDefs

prompts:
  # filter tab panels
  filterFade:
    type: string
    default: 'Fade'
  filterFadeHelp:
    type: string
    default: 'Show matches, Fade others'
  filterReduce:
    type: string
    default: 'Reduce'
  filterReduceHelp:
    type: string
    default: 'Show matches, Reduce (remove) others & recalculate sizes'
  filterFocus:
    type: string
    default: 'Focus'
  filterFocusHelp:
    type: string
    default: 'Show only nodes connected to the selected node within range'

# Defaults for the D3-based GraphView renderer
graphView:
  nodeSizeDefault:
    type: number
    default: 5
  nodeSizeMax:
    type: number
    default: 50
  edgeSizeDefault:
    type: number
    default: 1
  edgeSizeMax:
    type: number
    default: 25
  nodeDefaultTransparency:
    type: number
    default: 1
  edgeDefaultTransparency:
    type: number
    default: 0.7
  searchColor:
    type: number
    default: '#008800' # color used to hilight a search result
  sourceColor:
    type: number
    default: '#FFa500' # color used to hilight a source
